apiVersion: v1
kind: Service
metadata:
  name: dubbo-demo-service
  namespace: higress-system
  creationTimestamp: "2000-01-01T00:00:00Z"
  resourceVersion: "1"
spec:
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  type: ExternalName
  externalName: 172.18.0.2
