apiVersion: v1
kind: Secret
metadata:
  name: https-server-secret
  namespace: higress-system
  creationTimestamp: "2000-01-01T00:00:00Z"
  resourceVersion: "1"
type: kubernetes.io/tls
data:
  # http.crt (服务器证书) - base64编码
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNFekNDQWJtZ0F3SUJBZ0lVYkpQeWRzYVZldjZSTzN4K28zeDZRd0QwOFM4d0NnWUlLb1pJemowRUF3SXcKYlRFTE1Ba0dBMVVFQmhNQ1EwNHhFVEFQQmdOVkJBZ01DRk5vWVc1bmFHRnBNUkV3RHdZRFZRUUhEQWhUYUdGdQpaMmhoYVRFU01CQUdBMVVFQ2d3SlkyRnlhVzVuTFVOQk1Rc3dDUVlEVlFRTERBSkRRVEVYTUJVR0ExVUVBd3dPClkyRnlhVzVuTFZKdmIzUXRRMEV3SGhjTk1qWXdNekE0TURZek5UUXpXaGNOTWpjd016QTRNRFl6TlRReldqQmkKTVFzd0NRWURWUVFHRXdKRFRqRVJNQThHQTFVRUNBd0lVMmhoYm1kb1lXa3hFVEFQQmdOVkJBY01DRk5vWVc1bgphR0ZwTVE4d0RRWURWUVFLREFaallYSnBibWN4RFRBTEJnTlZCQXNNQkdoMGRIQXhEVEFMQmdOVkJBTU1CR2gwCmRIQXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUVZlQ0M4eFdxY0p5R01FdmdpK0JHai9UNTMKWENXNEprY3BHNSs1T1k5cmJ4RXBvbFIwZ3Q5Skpzb0Y5ZmVWWkQveFVzTjB0dVB1MkRiZWZQTTltUTVybzBJdwpRREFkQmdOVkhRNEVGZ1FVVkpteG1YMUpZYjloY2REU2lVZ0RsYm9CS2w4d0h3WURWUjBqQkJnd0ZvQVVtbTRDCm9KZ0hEVWMyOGVhRXlwNEdsZ3UraGx3d0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1VrOWRRUkJYaXgvdnBMT3YKZnJOeG4wSTdVNlljMmtnUUdocDdTUng4TW9zQ0lRRG5qZnA1VW03UkcrVFQ3Y1JzeURiV1FITFNoTTRsK285bApDNHhHZ2NDUGpBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  # http.key (服务器私钥 - PKCS#8格式) - base64编码
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2RUQ0JZbHYrNGlJOGhQeloKdmM4eXY0dm9zVGQ0TVhITk1Nb3VDTDVjQTB1aFJBTkNBQVFWZUNDOHhXcWNKeUdNRXZnaStCR2ovVDUzWENXNApKa2NwRzUrNU9ZOXJieEVwb2xSMGd0OUpKc29GOWZlVlpEL3hVc04wdHVQdTJEYmVmUE05bVE1cgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
