apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: higress-system
  annotations: {}
spec:
  ingressClassName: higress
  tls:
  - hosts:
    - "www.caringfamily.cn"
    secretName: https-server-secret
  rules:
  - host: "www.caringfamily.cn"
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: placeholder-service # 占位服务
            port:
              number: 80
      - path: /index.html
        pathType: Exact
        backend:
          service:
            name: placeholder-service
            port:
              number: 80