# Higress HTTPS 配置
# 包含 TLS Secret 和 higress-https ConfigMap

---
# HTTPS 证书 Secret
# 注意：使用前需要将证书和密钥进行 base64 编码填入
apiVersion: v1
kind: Secret
metadata:
  name: https-server-secret
  namespace: higress-system
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrekNDQXhxZ0F3SUJBZ0lTQnBiM0tNNXpieW5qQVMrbklLTHJLeGNSTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpPREFlRncweU5qQXpNRGt4TVRRd01EVmFGdzB5TmpBMk1EY3hNVFF3TURSYU1Cb3hHREFXQmdOVkJBTVREMk5oCmNtbHVaMlpoYldsc2VTNWpiakJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSFV5MndUR1dmMHEKYzExczRBNGlzdGM4SjUwMlN6YTlhczFMTC9nNFFCRWxhanBxUGZBSGFuUGtBSTZ3cm44TTJkUmZvN1U2MTJsagpjd2xWU2oxNjNwMmpnZ0ltTUlJQ0lqQU9CZ05WSFE4QkFmOEVCQU1DQjRBd0V3WURWUjBsQkF3d0NnWUlLd1lCCkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVsQzJnQjVIc0gzV1ByaTVBMVd4cXlYakgKUzE4d0h3WURWUjBqQkJnd0ZvQVVqdzBUb3ZZdWZ0RlFiRE1ZT0YxWmppTnlrY293TWdZSUt3WUJCUVVIQVFFRQpKakFrTUNJR0NDc0dBUVVGQnpBQ2hoWm9kSFJ3T2k4dlpUZ3VhUzVzWlc1amNpNXZjbWN2TUM4R0ExVWRFUVFvCk1DYUNEMk5oY21sdVoyWmhiV2xzZVM1amJvSVRkM2QzTG1OaGNtbHVaMlpoYldsc2VTNWpiakFUQmdOVkhTQUUKRERBS01BZ0dCbWVCREFFQ0FUQXRCZ05WSFI4RUpqQWtNQ0tnSUtBZWhoeG9kSFJ3T2k4dlpUZ3VZeTVzWlc1agpjaTV2Y21jdk1UZ3VZM0pzTUlJQkFnWUtLd1lCQkFIV2VRSUVBZ1NCOHdTQjhBRHVBSFVBWkJIRWJLUVM3S2VKCkhLSUNMZ0M4cTA4b0I5UWVOU2VyNnY3VkE4bDl6ZkFBQUFHYzBwcytlUUFBQkFNQVJqQkVBaUJ1Q3FTMWpRZSsKbW1FL3E1dGtZakhacllDbVhWMCs5SFhmalp0bFlqS1R6QUlnZHF4SWVaOUxrdWNFK1MzTWN0Y2hYTWgwVGJaRwpVSGJJMGw3VGsvS3dvWGNBZFFDV2wyUy9WVmlYcmZkRGgyZzNDRUozNmZBNjFmYWs4elp1UnFRL0Q4cXB4Z0FBCkFaelNtejdMQUFBRUF3QkdNRVFDSURvZFBVbnZvK1dwRng5Zit6U2Vucml5VEZ4ZVYyWVA4bklvL0VOMjRGUTAKQWlCMkltWmUycXd5cHNMWDUyR3lDQ0Z6eXRsQjIyU3U5YzdXU2E4ckZUalJPREFLQmdncWhrak9QUVFEQXdObgpBREJrQWpCNzc4UXlBUUtGU2VSa3lONHVHQ3N6eWo5czBYcE14UE5YTzJucjErMWxCTDBrdUNOdHJnL0Nmbkl6CnF1VTV3ajBDTURtM3BSTzNkL2xPM1JIdHJaNDcrUlJvOU1KSTJGazgxSkFHNzNxOUpBeFZRNVpiL1VxUXJUV0MKTWtGdHZaNlZ4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2Voem54dXZNdW9jbWl5c3QKSnV3c2M2aGZuY1lQV1hBa3BqbThwRks5WDBDaFJBTkNBQVIxTXRzRXhsbjlLbk5kYk9BT0lyTFhQQ2VkTmtzMgp2V3JOU3kvNE9FQVJKV282YWozd0IycHo1QUNPc0s1L0ROblVYNk8xT3RkcFkzTUpWVW85ZXQ2ZAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="

---
# CA 证书 Secret（mTLS 场景使用）
apiVersion: v1
kind: Secret
metadata:
  name: https-server-secret-cacert
  namespace: higress-system
type: Opaque
data:
  # cat ca.crt | base64 -w 0
  ca.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNMekNDQWRXZ0F3SUJBZ0lVU1lIZmlnb3JnZjJ4amhTdjhMRmZGWEpUM09jd0NnWUlLb1pJemowRUF3SXcKYlRFTE1Ba0dBMVVFQmhNQ1EwNHhFVEFQQmdOVkJBZ01DRk5vWVc1bmFHRnBNUkV3RHdZRFZRUUhEQWhUYUdGdQpaMmhoYVRFU01CQUdBMVVFQ2d3SlkyRnlhVzVuTFVOQk1Rc3dDUVlEVlFRTERBSkRRVEVYTUJVR0ExVUVBd3dPClkyRnlhVzVuTFZKdmIzUXRRMEV3SGhjTk1qWXdNekE0TURZek5USTRXaGNOTkRZd016QXpNRFl6TlRJNFdqQnQKTVFzd0NRWURWUVFHRXdKRFRqRVJNQThHQTFVRUNBd0lVMmhoYm1kb1lXa3hFVEFQQmdOVkJBY01DRk5vWVc1bgphR0ZwTVJJd0VBWURWUVFLREFsallYSnBibWN0UTBFeEN6QUpCZ05WQkFzTUFrTkJNUmN3RlFZRFZRUUREQTVqCllYSnBibWN0VW05dmRDMURRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTmgvUGU4R1dKNGwKVzNXbG12SCtRTUYxRjVQV2NEamQwb0dtKzRqamlrSEk0TjVFSkVrcnRYS3BmbGw2MHVlTTB0Rjh4ZmswbmZOYQpVUzJPS0gwYjN5S2pVekJSTUIwR0ExVWREZ1FXQkJTYWJnS2dtQWNOUnpieDVvVEtuZ2FXQzc2R1hEQWZCZ05WCkhTTUVHREFXZ0JTYWJnS2dtQWNOUnpieDVvVEtuZ2FXQzc2R1hEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01Bb0cKQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUUMvcnd4SGRRUy9YOGNYa2NFRERyZ0dmOGhVQ0pFNGF0OWJNc2tmNjRPKwpuUUlnY1VvSzJJelBGdDdZR0FENWxMNW56UmR3YjRJc0lPdHJ1Z0RtUXgrUFJwaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

---
# Higress HTTPS 配置 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: higress-https
  namespace: higress-system
data:
  cert: |
    automaticHttps: false
    credentialConfig:
    - domains:
      - www.caringfamily.cn
      tlsSecret: https-server-secret
    fallbackForInvalidSecret: false
    renewBeforeDays: 30
    version: "20260309000002"
