apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    managed-by: higress-deploy
  name: xiaozhi-server-ingress
  namespace: higress-system
  annotations:
    higress.io/backend-protocol: HTTP
    higress.io/destination: xiaozhi-server.static
    higress.io/auth-tls-secret: https-server-secret-cacert
    higress.io/auth-tls-verify-depth: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  ingressClassName: higress
  tls:
  - hosts:
    - x.caringfamily.cn
    secretName: https-server-secret
  rules:
  - host: x.caringfamily.cn
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
      - path: /ws
        pathType: Prefix
        backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default