apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    managed-by: higress-deploy
  name: xiaozhi-server-ingress
  namespace: higress-system
  annotations:
    higress.io/backend-protocol: HTTP
    higress.io/destination: xiaozhi-server.higress-system.static
    higress.io/auth-tls-secret: https-server-secret-cacert
    higress.io/auth-tls-verify-depth: "3"
    higress.io/proxy-read-timeout: "3600"
    higress.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: higress
  tls:
  - hosts:
    - x.caringfamily.cn
    secretName: https-server-secret
  rules:
  - host: x.caringfamily.cn
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: xiaozhi-server.higress-system.static
            port:
              number: 8091
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: xiaozhi-server.higress-system.static
            port:
              number: 8091