apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xiaozhi-server-ingress
  namespace: higress-system
  annotations:
    higress.io/backend-protocol: HTTP
    higress.io/auth-tls-secret: https-server-secret-cacert
    higress.io/auth-tls-verify-depth: "3"
spec:
  ingressClassName: higress
  tls:
  - hosts: ["xz.caringfamily.cn"]
    secretName: https-server-secret
  rules:
  - host: xz.caringfamily.cn
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: xiaozhi-server-static
            port:
              number: 8091
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: xiaozhi-server-static
            port:
              number: 8091
