apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
    - name: nacos
      type: nacos2
      domain: nacos
      port: 8848
      nacosNamespaceId: public
      nacosGroups:
        - PUBLIC-GROUP
