apiVersion: v1
kind: Service
metadata:
  name: xiaozhi-web-static
  namespace: higress-system
spec:
  ports:
    - port: 8085
---
apiVersion: v1
kind: Endpoints
metadata:
  name: xiaozhi-web-static
  namespace: higress-system
subsets:
  - addresses:
      - ip: 172.24.137.197
    ports:
      - port: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: xiaozhi-server-static
  namespace: higress-system
spec:
  ports:
    - port: 8091
---
apiVersion: v1
kind: Endpoints
metadata:
  name: xiaozhi-server-static
  namespace: higress-system
subsets:
  - addresses:
      - ip: 172.24.137.197
    ports:
      - port: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: higress-console-static
  namespace: higress-system
spec:
  ports:
    - port: 80
      targetPort: 8001 # 控制台监听的真实端口
---
apiVersion: v1
kind: Endpoints
metadata:
  name: higress-console-static
  namespace: higress-system
subsets:
  - addresses:
      - ip: 172.24.137.195 # 必须用物理内网 IP，不能用 127.0.0.1
    ports:
      - port: 8001
