apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeter-grpc-ingress
  namespace: higress-system
  annotations:
    higress.io/destination: dubbo-demo-service.higress-system.svc.cluster.local:50051
  creationTimestamp: "2000-01-01T00:00:00Z"
  resourceVersion: "1"
spec:
  ingressClassName: higress
  rules:
    - http:
        paths:
          - path: /com.pocrd.service_demo.api.GreeterServiceHttpExport
            pathType: Prefix
            backend:
              service:
                name: dubbo-demo-service
                port:
                  number: 50051
