apiVersion: v1
data:
  cert: |
    automaticHttps: false
    credentialConfig:
    - domains:
      - www.caringfamily.cn
      tlsSecret: https-server-secret
    fallbackForInvalidSecret: false
    renewBeforeDays: 30
    version: "20260309000002"
kind: ConfigMap
metadata:
  creationTimestamp: "2000-01-01T00:00:00Z"
  name: higress-https
  namespace: higress-system
  resourceVersion: "1"